# Generated by Django 4.2.3 on 2023-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('igd_id', models.AutoField(primary_key=True, serialize=False, verbose_name='성분id')),
                ('igd_name', models.CharField(max_length=20, verbose_name='성분명')),
                ('igd_main_ftn', models.TextField(verbose_name='성분메인기능')),
                ('igd_plants', models.BooleanField(null=True, verbose_name='식물성')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
