# Generated by Django 4.2.3 on 2023-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='igd_main_ftn',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='igd_plants',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='igd_caution',
            field=models.BooleanField(default=None, verbose_name='주의성분 포함여부'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='igd_ewg_data',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'limited'), (3, 'fair'), (4, 'good'), (5, 'robust')], null=True, verbose_name='EWG등급-데이터등급'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='igd_ewg_harzard',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'low harzard'), (3, 'moderate harzard'), (4, 'high harzard')], null=True, verbose_name='EWG등급-위험도등급'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='igd_ewg_harzard_no',
            field=models.CharField(max_length=10, null=True, verbose_name='EWG등급-위험도숫자'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='igd_info',
            field=models.CharField(default=None, max_length=70, verbose_name='성분 기타 정보'),
        ),
    ]
