# Generated by Django 4.2.3 on 2023-08-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('procuct_name', models.CharField(max_length=50, verbose_name='제품 이름')),
                ('product_price', models.IntegerField(verbose_name='제품 가격')),
                ('product_brand', models.CharField(max_length=20, verbose_name='제품 브랜드명')),
                ('product_purpose', models.CharField(max_length=500, verbose_name='제품 사용 목적')),
                ('pd_usage', models.CharField(max_length=500, verbose_name='제품 사용법')),
                ('pd_like_cnt', models.IntegerField(verbose_name='찜 개수')),
                ('cg_id', models.IntegerField(choices=[('1', '스킨케어'), ('2', '선케어'), ('3', '샴푸')])),
                ('cg_name', models.CharField(choices=[('1', '스킨케어'), ('2', '선케어'), ('3', '샴푸')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
