# Generated by Django 4.2.3 on 2023-08-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='pd_id',
            new_name='product',
        ),
    ]
