# Generated by Django 4.2.3 on 2023-08-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('mk_id', models.AutoField(primary_key=True, serialize=False)),
                ('mk_name', models.CharField(max_length=20, verbose_name='구매처 이름')),
                ('pd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
