# Generated by Django 4.2.3 on 2023-08-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_brand',
            new_name='pd_brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_id',
            new_name='pd_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='procuct_name',
            new_name='pd_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='pd_price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_purpose',
            new_name='pd_purpose',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cg_id',
        ),
    ]
