# Generated by Django 4.2.3 on 2023-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cg_id',
            field=models.IntegerField(choices=[(1, 'makeup'), (2, 'skincare'), (3, 'mask'), (4, 'suncare')]),
        ),
    ]
