# Generated by Django 4.2.3 on 2023-08-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_pd_id_market_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='mk_link',
            field=models.URLField(max_length=500),
        ),
    ]
