# Generated by Django 4.2.3 on 2023-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cg_id',
            field=models.IntegerField(choices=[('1', 'makeup'), ('2', 'skincare'), ('3', 'mask'), ('4', 'suncare')], default=None, null=True),
        ),
    ]
