# Generated by Django 4.2.3 on 2023-08-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_market_mk_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vg_id', models.IntegerField(choices=[('1', '한국비건인증원'), ('2', '프랑스 이브 비건'), ('3', '이탈리아 브이라벨'), ('4', '비건 소사이어티'), ('5', 'PETA Beauty without bunny - global animal test-free'), ('6', 'PETA Beauty without bunny - global animal test-free and vegan'), ('7', '벨기에 바이오리우스')], verbose_name='비건 인증처명')),
                ('vg_company', models.CharField(choices=[('1', '한국비건인증원'), ('2', '프랑스 이브 비건'), ('3', '이탈리아 브이라벨'), ('4', '비건 소사이어티'), ('5', 'PETA Beauty without bunny - global animal test-free'), ('6', 'PETA Beauty without bunny - global animal test-free and vegan'), ('7', '벨기에 바이오리우스')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
