# Generated by Django 4.2.3 on 2023-08-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_vegan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegan',
            name='id',
        ),
        migrations.AlterField(
            model_name='vegan',
            name='vg_company',
            field=models.CharField(choices=[('1', 'Korea agency of Vegan Certification and Services'), ('2', 'Expertise Vegan Europe (EVE VEGAN®)'), ('3', 'V Label Italia srl'), ('4', 'The Vegan Society'), ('5', 'PETA Beauty without bunny - global animal test-free'), ('6', 'PETA Beauty without bunny - global animal test-free and vegan'), ('7', 'Biorius')], max_length=20, verbose_name='비건 인증처명'),
        ),
        migrations.AlterField(
            model_name='vegan',
            name='vg_id',
            field=models.AutoField(choices=[('1', 'Korea agency of Vegan Certification and Services'), ('2', 'Expertise Vegan Europe (EVE VEGAN®)'), ('3', 'V Label Italia srl'), ('4', 'The Vegan Society'), ('5', 'PETA Beauty without bunny - global animal test-free'), ('6', 'PETA Beauty without bunny - global animal test-free and vegan'), ('7', 'Biorius')], primary_key=True, serialize=False),
        ),
    ]
