# Generated by Django 4.2.3 on 2023-08-10 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_remove_vegan_id_alter_vegan_vg_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegan',
            name='vg_company',
            field=models.CharField(choices=[('Korea agency of Vegan Certification and Services', '한국비건인증원'), ('Expertise Vegan Europe', '프랑스이브비건'), ('V Label Italia srl', '이탈리아브이라벨'), ('The Vegan Society', '영국비건소사이어티'), ('PETA Beauty without bunny - global animal test-free', 'PETA1'), ('PETA Beauty without bunny - global animal test-free and vegan', 'PETA2'), ('Biorius', '벨기에 바이오리우스')], max_length=70, verbose_name='비건 인증처명'),
        ),
        migrations.AlterField(
            model_name='vegan',
            name='vg_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wish_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_product_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
